services:
  mongodb:
    image: prodiegus/chatpyme-db:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

  servidor-chat:
    build: .
    ports:
      - "5000:5000"
    container_name: servidor_chat
    depends_on:
      - mongodb